# Add this file to the root of your dbt project and use environment variables
# to configure dev vs production. I recommend using direnv locally with .envrc files.

jaffle_shops:
  target: bigquery
  outputs:
    bigquery:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('DBT_GOOGLE_BIGQUERY_KEYFILE') }}"
      project: "{{ env_var('DBT_GOOGLE_PROJECT') }}"
      # dataset: "{{ env_var('DBT_GOOGLE_BIGQUERY_DATASET') }}"
      threads: 10
      timeout_seconds: 300
      location: US
      priority: interactive