# This is a basic workflow to help you get started with Actions

name: DBT Test on PR

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Env values for this Action  
env:
  DBT_PROFILES_DIR: ./
  DBT_GOOGLE_PROJECT: dbt-hello-world-305619
  DBT_GOOGLE_BIGQUERY_DATASET: dbt_john
  DBT_GOOGLE_BIGQUERY_KEYFILE: ./.gcloud/dbt-service-account.json


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # This value will be displayed to the user during runtime
    name: Running DBT Tests
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Install Python 3.8.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.8

    - name: Install DBT
      # Runs a set of commands using the runners shell
      run: |
        python -m pip install --upgrade pip
        pip install dbt

    - run: 'echo "$KEYFILE" > ./.gcloud/dbt-service-account.json'
      shell: bash
      env:
        KEYFILE: ${{secrets.DBT_GOOGLE_BIGQUERY_KEYFILE}}

    - name: Test dbt Connection
      run: dbt debug

    - name: Run dbt Transforms
      run: dbt run

    - name: Run dbt Tests
      run: dbt test
